// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgRW7PidSdwpvdv5WY5hkdTJ6x6S0DmEI',
    appId: '1:690559996874:web:bbc2bb7141c6765623f533',
    messagingSenderId: '690559996874',
    projectId: 'one-signal-notification-92d79',
    authDomain: 'one-signal-notification-92d79.firebaseapp.com',
    storageBucket: 'one-signal-notification-92d79.firebasestorage.app',
    measurementId: 'G-VDE8GMJV73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjdzkMfZKnow_b3_U2RwiemglaL8BZg8Q',
    appId: '1:690559996874:android:d313621a30952e1523f533',
    messagingSenderId: '690559996874',
    projectId: 'one-signal-notification-92d79',
    storageBucket: 'one-signal-notification-92d79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF-HgK1oFpVVScFFKVCiu3C1BcYrBluWM',
    appId: '1:690559996874:ios:2f0d5001e58e7ac423f533',
    messagingSenderId: '690559996874',
    projectId: 'one-signal-notification-92d79',
    storageBucket: 'one-signal-notification-92d79.firebasestorage.app',
    iosBundleId: 'com.example.crudBlocApiTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF-HgK1oFpVVScFFKVCiu3C1BcYrBluWM',
    appId: '1:690559996874:ios:2f0d5001e58e7ac423f533',
    messagingSenderId: '690559996874',
    projectId: 'one-signal-notification-92d79',
    storageBucket: 'one-signal-notification-92d79.firebasestorage.app',
    iosBundleId: 'com.example.crudBlocApiTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgRW7PidSdwpvdv5WY5hkdTJ6x6S0DmEI',
    appId: '1:690559996874:web:9ec725c2cac45d9c23f533',
    messagingSenderId: '690559996874',
    projectId: 'one-signal-notification-92d79',
    authDomain: 'one-signal-notification-92d79.firebaseapp.com',
    storageBucket: 'one-signal-notification-92d79.firebasestorage.app',
    measurementId: 'G-DDB9012FX6',
  );
}
